[package]
name = "tg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
tokio-tungstenite = "0.17.2"
chrono = "0.4.22"
hex = "0.4.3"
lockfree-object-pool = "0.1.3"
lazy_static = "1.4.0"
futures-util = "0.3.23"
async-trait = "0.1.57"
bytes = "1.2.1"
url = "2.2.2"
nix = "0.25.0"
type-layout = "0.2.0"
prost = "0.10"
tonic = "0.8.1"
tonic-build = "0.8.0"
tracing-appender = "0.2.2"
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter","time","local-time"] }
time = { version = "0.3", features = ["macros"] }