[package]
name = "tg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
tokio-tungstenite = "0.17.2"
protobuf = "3.1.0"
chrono = "0.4.19"
hex = "0.4.3"
thread-id = "4.0.0"
lockfree-object-pool = "0.1.3"
lazy_static = "1.4.0"
futures-util = "0.3.23"